# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sns.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sns.proto',
  package='csce438',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tsns.proto\x12\x07\x63sce438\x1a\x1fgoogle/protobuf/timestamp.proto\"1\n\tListReply\x12\x11\n\tall_users\x18\x01 \x03(\t\x12\x11\n\tfollowers\x18\x02 \x03(\t\".\n\x07Request\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x11\n\targuments\x18\x02 \x03(\t\"\x14\n\x05Reply\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x18\n\x05\x41live\x12\x0f\n\x07notDead\x18\x01 \x01(\x08\"W\n\x07Message\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\x8c\x03\n\nSNSService\x12+\n\x05Login\x12\x10.csce438.Request\x1a\x0e.csce438.Reply\"\x00\x12.\n\x04List\x12\x10.csce438.Request\x1a\x12.csce438.ListReply\"\x00\x12,\n\x06\x46ollow\x12\x10.csce438.Request\x1a\x0e.csce438.Reply\"\x00\x12.\n\x08UnFollow\x12\x10.csce438.Request\x1a\x0e.csce438.Reply\"\x00\x12-\n\tKeepAlive\x12\x0e.csce438.Alive\x1a\x0e.csce438.Alive\"\x00\x12\x30\n\x0cGetAvailable\x12\x0e.csce438.Alive\x1a\x0e.csce438.Reply\"\x00\x12,\n\x08\x45lection\x12\x0e.csce438.Alive\x1a\x0e.csce438.Alive\"\x00\x12\x34\n\x08Timeline\x12\x10.csce438.Message\x1a\x10.csce438.Message\"\x00(\x01\x30\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_LISTREPLY = _descriptor.Descriptor(
  name='ListReply',
  full_name='csce438.ListReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='all_users', full_name='csce438.ListReply.all_users', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='followers', full_name='csce438.ListReply.followers', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=104,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='csce438.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='csce438.Request.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arguments', full_name='csce438.Request.arguments', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=152,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='csce438.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='csce438.Reply.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=174,
)


_ALIVE = _descriptor.Descriptor(
  name='Alive',
  full_name='csce438.Alive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='notDead', full_name='csce438.Alive.notDead', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=200,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='csce438.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='csce438.Message.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='csce438.Message.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='csce438.Message.timestamp', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=289,
)

_MESSAGE.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['ListReply'] = _LISTREPLY
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
DESCRIPTOR.message_types_by_name['Alive'] = _ALIVE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListReply = _reflection.GeneratedProtocolMessageType('ListReply', (_message.Message,), dict(
  DESCRIPTOR = _LISTREPLY,
  __module__ = 'sns_pb2'
  # @@protoc_insertion_point(class_scope:csce438.ListReply)
  ))
_sym_db.RegisterMessage(ListReply)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'sns_pb2'
  # @@protoc_insertion_point(class_scope:csce438.Request)
  ))
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), dict(
  DESCRIPTOR = _REPLY,
  __module__ = 'sns_pb2'
  # @@protoc_insertion_point(class_scope:csce438.Reply)
  ))
_sym_db.RegisterMessage(Reply)

Alive = _reflection.GeneratedProtocolMessageType('Alive', (_message.Message,), dict(
  DESCRIPTOR = _ALIVE,
  __module__ = 'sns_pb2'
  # @@protoc_insertion_point(class_scope:csce438.Alive)
  ))
_sym_db.RegisterMessage(Alive)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'sns_pb2'
  # @@protoc_insertion_point(class_scope:csce438.Message)
  ))
_sym_db.RegisterMessage(Message)



_SNSSERVICE = _descriptor.ServiceDescriptor(
  name='SNSService',
  full_name='csce438.SNSService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=292,
  serialized_end=688,
  methods=[
  _descriptor.MethodDescriptor(
    name='Login',
    full_name='csce438.SNSService.Login',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='List',
    full_name='csce438.SNSService.List',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_LISTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Follow',
    full_name='csce438.SNSService.Follow',
    index=2,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UnFollow',
    full_name='csce438.SNSService.UnFollow',
    index=3,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='KeepAlive',
    full_name='csce438.SNSService.KeepAlive',
    index=4,
    containing_service=None,
    input_type=_ALIVE,
    output_type=_ALIVE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAvailable',
    full_name='csce438.SNSService.GetAvailable',
    index=5,
    containing_service=None,
    input_type=_ALIVE,
    output_type=_REPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Election',
    full_name='csce438.SNSService.Election',
    index=6,
    containing_service=None,
    input_type=_ALIVE,
    output_type=_ALIVE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Timeline',
    full_name='csce438.SNSService.Timeline',
    index=7,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SNSSERVICE)

DESCRIPTOR.services_by_name['SNSService'] = _SNSSERVICE

# @@protoc_insertion_point(module_scope)
